config/routes.rb
Rails.application.routes.draw do
  resources :things
  resources :users
  resources :manufacturers

  root 'things#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :things, -> { order created_at: :desc }
end

app/models/thing.rb
class Thing < ApplicationRecord
  has_one_attached :image
  belongs_to :manufacturer
  belongs_to :user

  validates :name, presence: true
  validates :purchase_date, comparison: { less_than: Time.now }
  validates :quantity, numericality: { only_integer: true }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :weight, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :image, presence: true

  [:price, :weight].each do |unit_method|
    define_method "total_#{unit_method}" do
      quantity * send(unit_method)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :things, -> { order created_at: :desc }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def safe_redirection_url(url, back_up_url = root_url)
    url_from(url) || back_up_url
  end

  def recover_flow_or_redirect_to(url, **options)
    if params['redirect_back_to']
      redirect_to safe_redirection_url(params['redirect_back_to'], url), **options
    else
      redirect_to url, **options
    end
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: %i[ show edit update destroy ]

  # GET /manufacturers or /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1 or /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers or /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { recover_flow_or_redirect_to manufacturer_url(@manufacturer), notice: "Manufacturer was successfully created." }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1 or /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to manufacturer_url(@manufacturer), notice: "Manufacturer was successfully updated." }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1 or /manufacturers/1.json
  def destroy
    @manufacturer.destroy

    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: "Manufacturer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_manufacturer
    @manufacturer = Manufacturer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def manufacturer_params
    params.require(:manufacturer).permit(:name, :description, :website, :email)
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: %i[ show edit update destroy ]

  # GET /things or /things.json
  def index
    @things = Thing.order created_at: :desc
  end

  # GET /things/1 or /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
    @thing.purchase_date = Time.now - 1.day
    @manufacturers = Manufacturer.all
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things or /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully created." }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1 or /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully updated." }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1 or /things/1.json
  def destroy
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url, notice: "Thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thing_params
      params.require(:thing).permit(:manufacturer_id, :user_id, :name, :description, :quantity, :price, :currency, :weight, :purchase_date, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { recover_flow_or_redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_redirect_field()
    return hidden_field_tag :redirect_back_to, params['redirect_back_to'] if params['redirect_back_to']
    ''
  end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
  def all_manufacturers
    Manufacturer.order(created_at: :desc).pluck(:name, :id)
  end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def all_users
    User.order(created_at: :desc).all.map {|user| [user.full_name, user.id]}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aozhome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "things", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "owner", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "layout", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'navigation/header' %>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/_form.html.erb
<%= form_with(model: manufacturer) do |form| %>
  <% if manufacturer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
        <% manufacturer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <%= hidden_redirect_field %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/manufacturers/_manufacturer.html.erb
<div id="<%= dom_id manufacturer %>" class="entity">
  <h2>
    <%= link_to manufacturer.name, manufacturer %>
    <small>made <%= pluralize manufacturer.things.count, 'thing' %></small>
  </h2>
  <div class="entity__action">
    <%= button_to "Edit", edit_manufacturer_path(manufacturers_path), method: :get %>
    <%= button_to "Delete", manufacturer, method: :delete %>
  </div>
</div>

app/views/manufacturers/edit.html.erb
<h1>Editing manufacturer</h1>

<%= render "form", manufacturer: @manufacturer %>

<br>

<div>
  <%= link_to "Show this manufacturer", @manufacturer %> |
  <%= link_to "Back to manufacturers", manufacturers_path %>
</div>

app/views/manufacturers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manufacturers</h1>

<%= link_to "New manufacturer", new_manufacturer_path %>

<div id="manufacturers">
  <% @manufacturers.each do |manufacturer| %>
    <%= render manufacturer %>
  <% end %>
</div>

app/views/manufacturers/new.html.erb
<h1>New manufacturer</h1>

<%= render "form", manufacturer: @manufacturer %>

app/views/manufacturers/show.html.erb
<%= render @manufacturer %>

<div class="things">
  <% @manufacturer.things.each do |thing| %>
    <%= render thing %>
  <% end %>
</div>

app/views/navigation/_header.html.erb
<header>
  <h1>Aozhome</h1>

  <nav>
    <ul>
      <li>
        <%= link_to 'Things', things_path %>
      </li>
      <li>
        <%= link_to 'Manufacturers', manufacturers_path %>
      </li>
      <li>
        <%= link_to 'Owners', users_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/things/_form.html.erb
<%= form_with(model: thing) do |form| %>
  <% if thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
        <% thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__row">
    <%= form.label :manufacturer_id, 'Manufacturer' %>
    <%= form.select :manufacturer_id, all_manufacturers %>
    <%= link_to 'New Manufacturer', new_manufacturer_path(redirect_back_to: request.path) %>
  </div>

  <div class="form__row">
    <%= form.label :user_id, 'Owner' %>
    <%= form.select :user_id, all_users %>
    <%= link_to 'New Owner', new_user_path(redirect_back_to: request.path) %>
  </div>

  <div class="form__row">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form__row">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form__row">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="form__row">
    <%= form.label :price %>
    <%= form.number_field :price %>
    <%= form.select :currency, ['NOK', 'CAD', 'EUR', 'USD', 'JPY'] %>
  </div>

  <div class="form__row">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
    g
  </div>

  <div class="form__row">
    <%= form.label :purchase_date %>
    <%= form.date_field :purchase_date %>
  </div>

  <%= form.file_field :image %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/things/_thing.html.erb
<div id="<%= dom_id thing %>" class="thing">
  <div class="thing__title">
    <h2>
      <%= link_to thing do %>
        <%= pluralize thing.quantity, thing.name %>
      <% end %>
    </h2>
    <p>
      <%= thing.description %>
    </p>
  </div>
  <div class="thing__image">
    <%= link_to thing.image, target: '_blank' do %>
      <%= image_tag thing.image %>
    <% end %>
  </div>
  <div class="thing__data">
    <div>
      Worth <%= thing.total_price %> <%= thing.currency %>
    </div>
    <div>
      Weighs <%= thing.total_weight %>g
    </div>
    <div>
      Purchased <%= time_tag thing.purchase_date, time_ago_in_words(thing.purchase_date) %> ago
    </div>
  </div>
</div>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Show this thing", @thing %> |
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Things</h1>
<%= link_to "New thing", new_thing_path %>

<div class="things">
  <% @things.each do |thing| %>
    <%= render thing %>
  <% end %>
</div>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thing %>

<div>
  <%= link_to "Edit this thing", edit_thing_path(@thing) %> |
  <%= link_to "Back to things", things_path %>

  <%= button_to "Destroy this thing", @thing, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <%= hidden_redirect_field %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="entity">
  <h2>
    <%= link_to user.full_name, user %>
    <small>owns <%= pluralize user.things.count, 'thing' %></small>
  </h2>
  <div class="entity__action">
    <%= button_to "Edit", edit_user_path(user), method: :get %>
    <%= button_to "Delete", user, method: :delete %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Owners</h1>

<%= link_to "New owner", new_user_path %>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= render @user %>

<div class="things">
  <% @user.things.each do |thing| %>
    <%= render thing %>
  <% end %>
</div>